version: "3.7"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    ports:
      - "3001:80"
    networks:
      - myNetwork

  api:
    extends:
      file: docker-compose.api.yml
      service: api
    depends_on:
      - rmq

  converter:
    container_name: converter
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    volumes:
      - ./.env:/app/.env
    networks:
      - myNetwork
    depends_on:
      - rmq

  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - myNetwork
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin


networks:
  myNetwork:
    driver: bridge