version: '3'

services:
  app:
    image: php:apache
    container_name: app
    ports:
      - "80:80"
    restart: unless-stopped

    # Use this to run app container after db and redis
    depends_on:
      - db
      - redis
    
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped