apiVersion: v1
kind: Service
metadata:
  name: kubernode-web-server

spec: 
  selector:
    app: kubernode-web-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer